# Generated by Django 4.2.7 on 2026-04-15 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JusticeNodeAISettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_confidence_score', models.DecimalField(decimal_places=2, help_text='AI Confidence 0-100%', max_digits=5)),
                ('suggested_client_refund_percentage', models.IntegerField(default=50)),
                ('suggested_artisan_payout_percentage', models.IntegerField(default=50)),
                ('reasoning', models.TextField(help_text='Detailed AI reasoning based on Milestones, Messages, and Contracts')),
                ('is_accepted_by_both', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settlement', to='disputes.dispute')),
            ],
        ),
    ]
