# Generated by Django 4.2.7 on 2026-04-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, help_text='{"en": "Verified Identity", "fr": "Identité Vérifiée"}')),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('description', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='artisans.badge'),
        ),
    ]
