# Generated by Django 4.2.7 on 2026-04-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='escrow_released',
            field=models.BooleanField(default=False),
        ),
    ]
