# Generated by Django 4.2.7 on 2026-04-15 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_escrow_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='KalideSupplyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(help_text='e.g. Hardware Store, IT Supplier', max_length=100)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_list', models.JSONField(help_text='List of materials or API payload')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Escrow Clearing'), ('funded', 'Vendor Funded'), ('delivered', 'Delivered to Site')], default='pending', max_length=20)),
                ('delivery_qr_code', models.CharField(blank=True, help_text='QR to scan on site', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to='projects.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kalidesupplypartner')),
            ],
        ),
        migrations.CreateModel(
            name='IoTTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='e.g. Smart Lock MAC or API token', max_length=255, unique=True)),
                ('activation_status', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iot_trigger', to='projects.milestone')),
            ],
        ),
    ]
