# Generated by Django 4.2.7 on 2026-04-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='translated_content',
            field=models.JSONField(blank=True, default=dict, help_text="Stores translations like {'fr': '...', 'es': '...'}"),
        ),
    ]
