# Generated by Django 4.2.7 on 2026-04-14 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, help_text='{"en": "Team Name", "fr": "Nom de l équipe"}')),
                ('description', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'marketplace_teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.JSONField(default=dict, help_text='{"en": "Role", "fr": "Role"}')),
            ],
            options={
                'db_table': 'marketplace_team_members',
            },
        ),
        migrations.CreateModel(
            name='TeamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisans.skillcategory')),
            ],
            options={
                'db_table': 'marketplace_team_templates',
            },
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.JSONField(default=dict)),
                ('required_skill', models.CharField(max_length=100)),
                ('team_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='bundles.teamtemplate')),
            ],
            options={
                'db_table': 'marketplace_team_roles',
            },
        ),
    ]
